[tool.poetry]
name = "revoltapilibrarything"
version = "0.1.0"
description = ""
authors = ["ERROR404NULL <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
